{% set version = "1.2.11.1" %}

package:
    name: zlib
    version: {{ version }}

source:
    git_url: https://github.com/jtkukunas/zlib
    git_rev: a43a247bfa16ec5368747b5b64f11ea5ca033010

build:
    number: 0
    run_exports:
        # mostly OK, but some scary symbol removal.  Let's try for trusting them.
        #    https://abi-laboratory.pro/tracker/timeline/zlib/
        - {{ pin_subpackage('zlib', max_pin='x.x') }}

requirements:
    build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}  # [win32]
        - cmake  # [win]
        - msinttypes  # [win and vc<14]
        - make  # [not win]
    host:
        - ripgrep

test:
    commands:
        - test -f ${PREFIX}/lib/libz.a  # [unix]

about:
    home: http://zlib.net/
    # http://zlib.net/zlib_license.html
    license: zlib
    summary: Massively spiffy yet delicately unobtrusive compression library
    license_family: Other
    license_file: license.txt
    
    description: |
      zlib is designed to be a free, general-purpose, lossless data-compression
      library for use on virtually any computer hardware and operating system.
    doc_url: http://zlib.net/manual.html
    dev_url: https://github.com/madler/zlib

extra:
    recipe-maintainers:
        - groutr
        - msarahan
        - ocefpaf
        - mingwandroid
